#!/bin/bash
# Convert a single PDF to markdown using marker_single

set -euo pipefail

if [ $# -ne 2 ]; then
    echo "Usage: $0 <input.pdf> <output.md>" >&2
    exit 1
fi

INPUT_PDF="$1"
OUTPUT_MD="$2"

# Validate input PDF exists
if [ ! -f "$INPUT_PDF" ]; then
    echo "Error: Input PDF not found: $INPUT_PDF" >&2
    exit 1
fi

# Create output directory if it doesn't exist
OUTPUT_DIR=$(dirname "$OUTPUT_MD")
if [ ! -d "$OUTPUT_DIR" ]; then
    mkdir -p "$OUTPUT_DIR"
fi

# Create a temporary directory for marker_single output
TEMP_DIR=$(mktemp -d)
trap "rm -rf '$TEMP_DIR'" EXIT

# Run marker_single
marker_single --output_dir "$TEMP_DIR" --output_format markdown "$INPUT_PDF"

# Find the generated markdown file
# marker_single typically creates a file named after the PDF (without extension) + .md
PDF_BASENAME=$(basename "$INPUT_PDF" .pdf)
GENERATED_MD="$TEMP_DIR/${PDF_BASENAME}.md"

# If that doesn't exist, try to find any .md file in the temp directory
if [ ! -f "$GENERATED_MD" ]; then
    GENERATED_MD=$(find "$TEMP_DIR" -name "*.md" -type f | head -n 1)
    if [ -z "$GENERATED_MD" ]; then
        echo "Error: No markdown file generated by marker_single" >&2
        exit 1
    fi
fi

# Copy the generated markdown to the output location
cp "$GENERATED_MD" "$OUTPUT_MD"

echo "Converted $INPUT_PDF to $OUTPUT_MD"
